export const QUERY_KEYS = {
  players: 'players',
  player: 'player',
  statistics: 'statistics',
  sessions: 'sessions',
  counts: 'counts',
  compare: 'compare',
  settings: 'settings',
  games: 'games',
  game: 'game',
  bgg: 'bgg',
  expansions: 'expansions',
  locations: 'locations',
  dashboard: 'dashboard',
  charts: 'charts',
  languages: 'languages',
  environment: 'environment',
};
