/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as PlayersIndexRouteImport } from './routes/players/index'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as SessionsNewRouteImport } from './routes/sessions/new'
import { Route as PlayersPlayerIdRouteImport } from './routes/players/$playerId'
import { Route as GamesNewRouteImport } from './routes/games/new'
import { Route as GamesGameIdRouteImport } from './routes/games/$gameId'
import { Route as SessionsUpdateSessionIdRouteImport } from './routes/sessions/update_.$sessionId'
import { Route as SessionsNewGameIdRouteImport } from './routes/sessions/new_.$gameId'
import { Route as PlayersPlayerIdSessionsRouteImport } from './routes/players/$playerId_.sessions'
import { Route as GamesGameIdUpdateRouteImport } from './routes/games/$gameId_.update'
import { Route as GamesGameIdSessionsRouteImport } from './routes/games/$gameId_.sessions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsNewRoute = SessionsNewRouteImport.update({
  id: '/sessions/new',
  path: '/sessions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesNewRoute = GamesNewRouteImport.update({
  id: '/games/new',
  path: '/games/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsUpdateSessionIdRoute = SessionsUpdateSessionIdRouteImport.update({
  id: '/sessions/update_/$sessionId',
  path: '/sessions/update/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsNewGameIdRoute = SessionsNewGameIdRouteImport.update({
  id: '/sessions/new_/$gameId',
  path: '/sessions/new/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdSessionsRoute = PlayersPlayerIdSessionsRouteImport.update({
  id: '/players/$playerId_/sessions',
  path: '/players/$playerId/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdUpdateRoute = GamesGameIdUpdateRouteImport.update({
  id: '/games/$gameId_/update',
  path: '/games/$gameId/update',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdSessionsRoute = GamesGameIdSessionsRouteImport.update({
  id: '/games/$gameId_/sessions',
  path: '/games/$gameId/sessions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/games/new': typeof GamesNewRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/games': typeof GamesIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/players': typeof PlayersIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/games/$gameId/sessions': typeof GamesGameIdSessionsRoute
  '/games/$gameId/update': typeof GamesGameIdUpdateRoute
  '/players/$playerId/sessions': typeof PlayersPlayerIdSessionsRoute
  '/sessions/new/$gameId': typeof SessionsNewGameIdRoute
  '/sessions/update/$sessionId': typeof SessionsUpdateSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/games/new': typeof GamesNewRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/games': typeof GamesIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/players': typeof PlayersIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/games/$gameId/sessions': typeof GamesGameIdSessionsRoute
  '/games/$gameId/update': typeof GamesGameIdUpdateRoute
  '/players/$playerId/sessions': typeof PlayersPlayerIdSessionsRoute
  '/sessions/new/$gameId': typeof SessionsNewGameIdRoute
  '/sessions/update/$sessionId': typeof SessionsUpdateSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/games/new': typeof GamesNewRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/games/': typeof GamesIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/games/$gameId_/sessions': typeof GamesGameIdSessionsRoute
  '/games/$gameId_/update': typeof GamesGameIdUpdateRoute
  '/players/$playerId_/sessions': typeof PlayersPlayerIdSessionsRoute
  '/sessions/new_/$gameId': typeof SessionsNewGameIdRoute
  '/sessions/update_/$sessionId': typeof SessionsUpdateSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/games/$gameId'
    | '/games/new'
    | '/players/$playerId'
    | '/sessions/new'
    | '/games'
    | '/locations'
    | '/players'
    | '/settings'
    | '/games/$gameId/sessions'
    | '/games/$gameId/update'
    | '/players/$playerId/sessions'
    | '/sessions/new/$gameId'
    | '/sessions/update/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/games/$gameId'
    | '/games/new'
    | '/players/$playerId'
    | '/sessions/new'
    | '/games'
    | '/locations'
    | '/players'
    | '/settings'
    | '/games/$gameId/sessions'
    | '/games/$gameId/update'
    | '/players/$playerId/sessions'
    | '/sessions/new/$gameId'
    | '/sessions/update/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/games/$gameId'
    | '/games/new'
    | '/players/$playerId'
    | '/sessions/new'
    | '/games/'
    | '/locations/'
    | '/players/'
    | '/settings/'
    | '/games/$gameId_/sessions'
    | '/games/$gameId_/update'
    | '/players/$playerId_/sessions'
    | '/sessions/new_/$gameId'
    | '/sessions/update_/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  GamesNewRoute: typeof GamesNewRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  SessionsNewRoute: typeof SessionsNewRoute
  GamesIndexRoute: typeof GamesIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  GamesGameIdSessionsRoute: typeof GamesGameIdSessionsRoute
  GamesGameIdUpdateRoute: typeof GamesGameIdUpdateRoute
  PlayersPlayerIdSessionsRoute: typeof PlayersPlayerIdSessionsRoute
  SessionsNewGameIdRoute: typeof SessionsNewGameIdRoute
  SessionsUpdateSessionIdRoute: typeof SessionsUpdateSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/new': {
      id: '/sessions/new'
      path: '/sessions/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof SessionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/new': {
      id: '/games/new'
      path: '/games/new'
      fullPath: '/games/new'
      preLoaderRoute: typeof GamesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/update_/$sessionId': {
      id: '/sessions/update_/$sessionId'
      path: '/sessions/update/$sessionId'
      fullPath: '/sessions/update/$sessionId'
      preLoaderRoute: typeof SessionsUpdateSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/new_/$gameId': {
      id: '/sessions/new_/$gameId'
      path: '/sessions/new/$gameId'
      fullPath: '/sessions/new/$gameId'
      preLoaderRoute: typeof SessionsNewGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerId_/sessions': {
      id: '/players/$playerId_/sessions'
      path: '/players/$playerId/sessions'
      fullPath: '/players/$playerId/sessions'
      preLoaderRoute: typeof PlayersPlayerIdSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId_/update': {
      id: '/games/$gameId_/update'
      path: '/games/$gameId/update'
      fullPath: '/games/$gameId/update'
      preLoaderRoute: typeof GamesGameIdUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId_/sessions': {
      id: '/games/$gameId_/sessions'
      path: '/games/$gameId/sessions'
      fullPath: '/games/$gameId/sessions'
      preLoaderRoute: typeof GamesGameIdSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  GamesNewRoute: GamesNewRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  SessionsNewRoute: SessionsNewRoute,
  GamesIndexRoute: GamesIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  PlayersIndexRoute: PlayersIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  GamesGameIdSessionsRoute: GamesGameIdSessionsRoute,
  GamesGameIdUpdateRoute: GamesGameIdUpdateRoute,
  PlayersPlayerIdSessionsRoute: PlayersPlayerIdSessionsRoute,
  SessionsNewGameIdRoute: SessionsNewGameIdRoute,
  SessionsUpdateSessionIdRoute: SessionsUpdateSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
