<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Ardalis.Specification" Version="9.3.1" />
        <PackageReference Include="Ardalis.Specification.EntityFrameworkCore" Version="9.3.1" />
        <PackageReference Include="BoardGamer.BoardGameGeek" Version="0.10.0" />
        <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
        <PackageReference Include="MailKit" Version="4.17.0" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.*" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.*" />
        <PackageReference Include="Microsoft.Extensions.AI" Version="10.9.0" />
        <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.9.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.*" />
        <PackageReference Include="OllamaSharp" Version="5.4.30" />
        <PackageReference Include="PdfPig" Version="[0.1.16]" />
        <PackageReference Include="Pgvector.EntityFrameworkCore" Version="0.3.0" />
        <PackageReference Include="Refit" Version="10.2.0" />
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\BoardGameTracker.Common\BoardGameTracker.Common.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Datastore\Migrations\Postgres\" />
    </ItemGroup>

</Project>
