<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Ardalis.Specification" />
        <PackageReference Include="Ardalis.Specification.EntityFrameworkCore" />
        <PackageReference Include="BoardGamer.BoardGameGeek" />
        <PackageReference Include="MailKit" />
        <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.Extensions.AI" />
        <PackageReference Include="Microsoft.Extensions.AI.OpenAI" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
        <PackageReference Include="OllamaSharp" />
        <PackageReference Include="PdfPig" />
        <PackageReference Include="Pgvector.EntityFrameworkCore" />
        <PackageReference Include="Refit" />
        <PackageReference Include="SixLabors.ImageSharp" />
        <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\BoardGameTracker.Common\BoardGameTracker.Common.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Datastore\Migrations\Postgres\" />
    </ItemGroup>

</Project>
