// <auto-generated />
using System;
using BoardGameTracker.Core.Datastore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BoardGameTracker.Core.DataStore.Migrations.Postgres
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20260103071226_AddedLoan")]
    partial class AddedLoan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BadgePlayer", b =>
                {
                    b.Property<int>("BadgesId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayersId")
                        .HasColumnType("integer");

                    b.HasKey("BadgesId", "PlayersId");

                    b.HasIndex("PlayersId");

                    b.ToTable("BadgePlayer");
                });

            modelBuilder.Entity("BoardGameTracker.Common.Entities.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DescriptionKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<string>("TitleKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescriptionKey = "different-games.green.description",
                            Image = "different-games-green.png",
                            Level = "Green",
                            TitleKey = "different-games.green.title",
                            Type = "DifferentGames"
                        },
                        new
                        {
                            Id = 2,
                            DescriptionKey = "different-games.blue.description",
                            Image = "different-games-blue.png",
                            Level = "Blue",
                            TitleKey = "different-games.blue.title",
                            Type = "DifferentGames"
                        },
                        new
                        {
                            Id = 3,
                            DescriptionKey = "different-games.red.description",
                            Image = "different-games-red.png",
                            Level = "Red",
                            TitleKey = "different-games.red.title",
                            Type = "DifferentGames"
                        },
                        new
                        {
                            Id = 4,
                            DescriptionKey = "different-games.gold.description",
                            Image = "different-games-gold.png",
                            Level = "Gold",
                            TitleKey = "different-games.gold.title",
                            Type = "DifferentGames"
                        },
                        new
                        {
                            Id = 5,
                            DescriptionKey = "sessions.green.description",
                            Image = "sessions-green.png",
                            Level = "Green",
                            TitleKey = "sessions.green.title",
                            Type = "Sessions"
                        },
                        new
                        {
                            Id = 6,
                            DescriptionKey = "sessions.blue.description",
                            Image = "sessions-blue.png",
                            Level = "Blue",
                            TitleKey = "sessions.blue.title",
                            Type = "Sessions"
                        },
                        new
                        {
                            Id = 7,
                            DescriptionKey = "sessions.red.description",
                            Image = "sessions-red.png",
                            Level = "Red",
                            TitleKey = "sessions.red.title",
                            Type = "Sessions"
                        },
                        new
                        {
                            Id = 8,
                            DescriptionKey = "sessions.gold.description",
                            Image = "sessions-gold.png",
                            Level = "Gold",
                            TitleKey = "sessions.gold.title",
                            Type = "Sessions"
                        },
                        new
                        {
                            Id = 9,
                            DescriptionKey = "wins.green.description",
                            Image = "wins-green.png",
                            Level = "Green",
                            TitleKey = "wins.green.title",
                            Type = "Wins"
                        },
                        new
                        {
                            Id = 10,
                            DescriptionKey = "wins.blue.description",
                            Image = "wins-blue.png",
                            Level = "Blue",
                            TitleKey = "wins.blue.title",
                            Type = "Wins"
                        },
                        new
                        {
                            Id = 11,
                            DescriptionKey = "wins.red.description",
                            Image = "wins-red.png",
                            Level = "Red",
                            TitleKey = "wins.red.title",
                            Type = "Wins"
                        },
                        new
                        {
                            Id = 12,
                            DescriptionKey = "wins.gold.description",
                            Image = "wins-gold.png",
                            Level = "Gold",
                            TitleKey = "wins.gold.title",
                            Type = "Wins"
                        },
                        new
                        {
                            Id = 13,
                            DescriptionKey = "duration.green.description",
                            Image = "duration-green.png",
                            Level = "Green",
                            TitleKey = "duration.green.title",
                            Type = "Duration"
                        },
                        new
                        {
                            Id = 14,
                            DescriptionKey = "duration.blue.description",
                            Image = "duration-blue.png",
                            Level = "Blue",
                            TitleKey = "duration.blue.title",
                            Type = "Duration"
                        },
                        new
                        {
                            Id = 15,
                            DescriptionKey = "duration.red.description",
                            Image = "duration-red.png",
                            Level = "Red",
                            TitleKey = "duration.red.title",
                            Type = "Duration"
                        },
                        new
                        {
                            Id = 16,
                            DescriptionKey = "duration.gold.description",
                            Image = "duration-gold.png",
                            Level = "Gold",
                            TitleKey = "duration.gold.title",
                            Type = "Duration"
                        },
                        new
                        {
                            Id = 17,
                            DescriptionKey = "win-percentage.green.description",
                            Image = "win-percentage-green.png",
                            Level = "Green",
                            TitleKey = "win-percentage.green.title",
                            Type = "WinPercentage"
                        },
                        new
                        {
                            Id = 18,
                            DescriptionKey = "win-percentage.blue.description",
                            Image = "win-percentage-blue.png",
                            Level = "Blue",
                            TitleKey = "win-percentage.blue.title",
                            Type = "WinPercentage"
                        },
                        new
                        {
                            Id = 19,
                            DescriptionKey = "win-percentage.red.description",
                            Image = "win-percentage-red.png",
                            Level = "Red",
                            TitleKey = "win-percentage.red.title",
                            Type = "WinPercentage"
                        },
                        new
                        {
                            Id = 20,
                            DescriptionKey = "win-percentage.gold.description",
                            Image = "win-percentage-gold.png",
                            Level = "Gold",
                            TitleKey = "win-percentage.gold.title",
                            Type = "WinPercentage"
                        },
                        new
                        {
                            Id = 21,
                            DescriptionKey = "solo-specialist.green.description",
                            Image = "solo-specialist-green.png",
                            Level = "Green",
                            TitleKey = "solo-specialist.green.title",
                            Type = "SoloSpecialist"
                        },
                        new
                        {
                            Id = 22,
                            DescriptionKey = "solo-specialist.blue.description",
                            Image = "solo-specialist-blue.png",
                            Level = "Blue",
                            TitleKey = "solo-specialist.blue.title",
                            Type = "SoloSpecialist"
                        },
                        new
                        {
                            Id = 23,
                            DescriptionKey = "solo-specialist.red.description",
                            Image = "solo-specialist-red.png",
                            Level = "Red",
                            TitleKey = "solo-specialist.red.title",
                            Type = "SoloSpecialist"
                        },
                        new
                        {
                            Id = 24,
                            DescriptionKey = "solo-specialist.gold.description",
                            Image = "solo-specialist-gold.png",
                            Level = "Gold",
                            TitleKey = "solo-specialist.gold.title",
                            Type = "SoloSpecialist"
                        },
                        new
                        {
                            Id = 25,
                            DescriptionKey = "winning-streak.green.description",
                            Image = "winning-streak-green.png",
                            Level = "Green",
                            TitleKey = "winning-streak.green.title",
                            Type = "WinningStreak"
                        },
                        new
                        {
                            Id = 26,
                            DescriptionKey = "winning-streak.blue.description",
                            Image = "winning-streak-blue.png",
                            Level = "Blue",
                            TitleKey = "winning-streak.blue.title",
                            Type = "WinningStreak"
                        },
                        new
                        {
                            Id = 27,
                            DescriptionKey = "winning-streak.red.description",
                            Image = "winning-streak-red.png",
                            Level = "Red",
                            TitleKey = "winning-streak.red.title",
                            Type = "WinningStreak"
                        },
                        new
                        {
                            Id = 28,
                            DescriptionKey = "winning-streak.gold.description",
                            Image = "winning-streak-gold.png",
                            Level = "Gold",
                            TitleKey = "winning-streak.gold.title",
                            Type = "WinningStreak"
                        },
                        new
                        {
                            Id = 29,
                            DescriptionKey = "social-player.green.description",
                            Image = "social-player-green.png",
                            Level = "Green",
                            TitleKey = "social-player.green.title",
                            Type = "SocialPlayer"
                        },
                        new
                        {
                            Id = 30,
                            DescriptionKey = "social-player.blue.description",
                            Image = "social-player-blue.png",
                            Level = "Blue",
                            TitleKey = "social-player.blue.title",
                            Type = "SocialPlayer"
                        },
                        new
                        {
                            Id = 31,
                            DescriptionKey = "social-player.red.description",
                            Image = "social-player-red.png",
                            Level = "Red",
                            TitleKey = "social-player.red.title",
                            Type = "SocialPlayer"
                        },
                        new
                        {
                            Id = 32,
                            DescriptionKey = "social-player.gold.description",
                            Image = "social-player-gold.png",
                            Level = "Gold",
                            TitleKey = "social-player.gold.title",
                            Type = "SocialPlayer"
                        },
                        new
                        {
                            Id = 33,
                            DescriptionKey = "close-win.description",
                            Image = "close-win.png",
                            TitleKey = "close-win.title",
                            Type = "CloseWin"
                        },
                        new
                        {
                            Id = 34,
                            DescriptionKey = "close-loss.description",
                            Image = "close-loss.png",
                            TitleKey = "close-loss.title",
                            Type = "CLoseLoss"
                        },
                        new
                        {
                            Id = 35,
                            DescriptionKey = "marathon-runner.description",
                            Image = "marathon.png",
                            TitleKey = "marathon-runner.title",
                            Type = "MarathonRunner"
                        },
                        new
                        {
                            Id = 36,
                            DescriptionKey = "first-try.description",
                            Image = "first-try.png",
                            TitleKey = "first-try.title",
                            Type = "FirstTry"
                        },
                        new
                        {
                            Id = 37,
                            DescriptionKey = "learning-curve.description",
                            Image = "learning-curve.png",
                            TitleKey = "learning-curve.title",
                            Type = "LearningCurve"
                        },
                        new
                        {
                            Id = 38,
                            DescriptionKey = "monthly-goal.description",
                            Image = "monthly-goal.png",
                            TitleKey = "monthly-goal.title",
                            Type = "MonthlyGoal"
                        },
                        new
                        {
                            Id = 39,
                            DescriptionKey = "consistent-schedule.description",
                            Image = "consistent-schedule.png",
                            TitleKey = "consistent-schedule.title",
                            Type = "ConsistentSchedule"
                        });
                });

            modelBuilder.Entity("BoardGameTracker.Common.Entities.Config", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Config");
                });

            modelBuilder.Entity("BoardGameTracker.Common.Entities.Expansion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BggId")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Expansions");
                });

            modelBuilder.Entity("BoardGameTracker.Common.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AdditionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("BggId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasScoring")
                        .HasColumnType("boolean");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<int?>("MinAge")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("YearPublished")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("BoardGameTracker.Common.Entities.GameAccessory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameAccessories");
                });

            modelBuilder.Entity("BoardGameTracker.Common.Entities.GameCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GameCategories");
                });

            modelBuilder.Entity("BoardGameTracker.Common.Entities.GameMechanic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GameMechanics");
                });

            modelBuilder.Entity("BoardGameTracker.Common.Entities.Helpers.PlayerSession", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<bool>("FirstPlay")
                        .HasColumnType("boolean");

                    b.Property<double?>("Score")
                        .HasColumnType("double precision");

                    b.Property<bool>("Won")
                        .HasColumnType("boolean");

                    b.HasKey("PlayerId", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("PlayerSessions");
                });

            modelBuilder.Entity("BoardGameTracker.Common.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int?>("GamePlayId")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PlayId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("BoardGameTracker.Common.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TranslationKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "en-us",
                            TranslationKey = "english"
                        },
                        new
                        {
                            Id = 2,
                            Key = "nl-be",
                            TranslationKey = "dutch"
                        });
                });

            modelBuilder.Entity("BoardGameTracker.Common.Entities.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LoanDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReturnedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("BoardGameTracker.Common.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("BoardGameTracker.Common.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("BoardGameTracker.Common.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("BoardGameTracker.Common.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("LocationId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("ExpansionSession", b =>
                {
                    b.Property<int>("ExpansionsId")
                        .HasColumnType("integer");

                    b.Property<int>("SessionsId")
                        .HasColumnType("integer");

                    b.HasKey("ExpansionsId", "SessionsId");

                    b.HasIndex("SessionsId");

                    b.ToTable("ExpansionSession");
                });

            modelBuilder.Entity("GameGameCategory", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("integer");

                    b.Property<int>("GamesId")
                        .HasColumnType("integer");

                    b.HasKey("CategoriesId", "GamesId");

                    b.HasIndex("GamesId");

                    b.ToTable("GameGameCategory");
                });

            modelBuilder.Entity("GameGameMechanic", b =>
                {
                    b.Property<int>("GamesId")
                        .HasColumnType("integer");

                    b.Property<int>("MechanicsId")
                        .HasColumnType("integer");

                    b.HasKey("GamesId", "MechanicsId");

                    b.HasIndex("MechanicsId");

                    b.ToTable("GameGameMechanic");
                });

            modelBuilder.Entity("GamePerson", b =>
                {
                    b.Property<int>("GamesId")
                        .HasColumnType("integer");

                    b.Property<int>("PeopleId")
                        .HasColumnType("integer");

                    b.HasKey("GamesId", "PeopleId");

                    b.HasIndex("PeopleId");

                    b.ToTable("GamePerson");
                });

            modelBuilder.Entity("BadgePlayer", b =>
                {
                    b.HasOne("BoardGameTracker.Common.Entities.Badge", null)
                        .WithMany()
                        .HasForeignKey("BadgesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoardGameTracker.Common.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BoardGameTracker.Common.Entities.Expansion", b =>
                {
                    b.HasOne("BoardGameTracker.Common.Entities.Game", "Game")
                        .WithMany("Expansions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("BoardGameTracker.Common.Entities.Game", b =>
                {
                    b.OwnsOne("BoardGameTracker.Common.ValueObjects.Price", "BuyingPrice", b1 =>
                        {
                            b1.Property<int>("GameId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("BuyingPrice");

                            b1.HasKey("GameId");

                            b1.ToTable("Games");

                            b1.WithOwner()
                                .HasForeignKey("GameId");
                        });

                    b.OwnsOne("BoardGameTracker.Common.ValueObjects.Price", "SoldPrice", b1 =>
                        {
                            b1.Property<int>("GameId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("SoldPrice");

                            b1.HasKey("GameId");

                            b1.ToTable("Games");

                            b1.WithOwner()
                                .HasForeignKey("GameId");
                        });

                    b.OwnsOne("BoardGameTracker.Common.ValueObjects.PlayTimeRange", "PlayTime", b1 =>
                        {
                            b1.Property<int>("GameId")
                                .HasColumnType("integer");

                            b1.Property<int>("MaxMinutes")
                                .HasColumnType("integer")
                                .HasColumnName("MaxPlayTime");

                            b1.Property<int>("MinMinutes")
                                .HasColumnType("integer")
                                .HasColumnName("MinPlayTime");

                            b1.HasKey("GameId");

                            b1.ToTable("Games");

                            b1.WithOwner()
                                .HasForeignKey("GameId");
                        });

                    b.OwnsOne("BoardGameTracker.Common.ValueObjects.PlayerCountRange", "PlayerCount", b1 =>
                        {
                            b1.Property<int>("GameId")
                                .HasColumnType("integer");

                            b1.Property<int>("Max")
                                .HasColumnType("integer")
                                .HasColumnName("MaxPlayers");

                            b1.Property<int>("Min")
                                .HasColumnType("integer")
                                .HasColumnName("MinPlayers");

                            b1.HasKey("GameId");

                            b1.ToTable("Games");

                            b1.WithOwner()
                                .HasForeignKey("GameId");
                        });

                    b.OwnsOne("BoardGameTracker.Common.ValueObjects.Rating", "Rating", b1 =>
                        {
                            b1.Property<int>("GameId")
                                .HasColumnType("integer");

                            b1.Property<double>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("double precision")
                                .HasColumnName("Rating");

                            b1.HasKey("GameId");

                            b1.ToTable("Games");

                            b1.WithOwner()
                                .HasForeignKey("GameId");
                        });

                    b.OwnsOne("BoardGameTracker.Common.ValueObjects.Weight", "Weight", b1 =>
                        {
                            b1.Property<int>("GameId")
                                .HasColumnType("integer");

                            b1.Property<double>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("double precision")
                                .HasColumnName("Weight");

                            b1.HasKey("GameId");

                            b1.ToTable("Games");

                            b1.WithOwner()
                                .HasForeignKey("GameId");
                        });

                    b.Navigation("BuyingPrice");

                    b.Navigation("PlayTime");

                    b.Navigation("PlayerCount");

                    b.Navigation("Rating");

                    b.Navigation("SoldPrice");

                    b.Navigation("Weight");
                });

            modelBuilder.Entity("BoardGameTracker.Common.Entities.GameAccessory", b =>
                {
                    b.HasOne("BoardGameTracker.Common.Entities.Game", "Game")
                        .WithMany("Accessories")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("BoardGameTracker.Common.Entities.Helpers.PlayerSession", b =>
                {
                    b.HasOne("BoardGameTracker.Common.Entities.Player", "Player")
                        .WithMany("PlayerSessions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoardGameTracker.Common.Entities.Session", "Session")
                        .WithMany("PlayerSessions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("BoardGameTracker.Common.Entities.Image", b =>
                {
                    b.HasOne("BoardGameTracker.Common.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoardGameTracker.Common.Entities.Session", "Play")
                        .WithMany("ExtraImages")
                        .HasForeignKey("PlayId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Game");

                    b.Navigation("Play");
                });

            modelBuilder.Entity("BoardGameTracker.Common.Entities.Loan", b =>
                {
                    b.HasOne("BoardGameTracker.Common.Entities.Game", "Game")
                        .WithMany("Loans")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoardGameTracker.Common.Entities.Player", "Player")
                        .WithMany("Loans")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BoardGameTracker.Common.Entities.Session", b =>
                {
                    b.HasOne("BoardGameTracker.Common.Entities.Game", "Game")
                        .WithMany("Sessions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoardGameTracker.Common.Entities.Location", "Location")
                        .WithMany("Sessions")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Game");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("ExpansionSession", b =>
                {
                    b.HasOne("BoardGameTracker.Common.Entities.Expansion", null)
                        .WithMany()
                        .HasForeignKey("ExpansionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoardGameTracker.Common.Entities.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameGameCategory", b =>
                {
                    b.HasOne("BoardGameTracker.Common.Entities.GameCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoardGameTracker.Common.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameGameMechanic", b =>
                {
                    b.HasOne("BoardGameTracker.Common.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoardGameTracker.Common.Entities.GameMechanic", null)
                        .WithMany()
                        .HasForeignKey("MechanicsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamePerson", b =>
                {
                    b.HasOne("BoardGameTracker.Common.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoardGameTracker.Common.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PeopleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BoardGameTracker.Common.Entities.Game", b =>
                {
                    b.Navigation("Accessories");

                    b.Navigation("Expansions");

                    b.Navigation("Loans");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("BoardGameTracker.Common.Entities.Location", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("BoardGameTracker.Common.Entities.Player", b =>
                {
                    b.Navigation("Loans");

                    b.Navigation("PlayerSessions");
                });

            modelBuilder.Entity("BoardGameTracker.Common.Entities.Session", b =>
                {
                    b.Navigation("ExtraImages");

                    b.Navigation("PlayerSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
