<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <SpaRoot>..\boardgametracker.client\</SpaRoot>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <SpaProxyLaunchCommand>pnpm dev</SpaProxyLaunchCommand>
        <SpaProxyServerUrl>http://localhost:5443</SpaProxyServerUrl>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
        <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
        <PackageReference Include="Microsoft.AspNetCore.SpaProxy" />
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Refit.HttpClientFactory" />
        <PackageReference Include="Refit.Reflection" />
        <PackageReference Include="Serilog.AspNetCore" />
        <PackageReference Include="Serilog.Sinks.Console" />
        <PackageReference Include="Serilog.Sinks.File" />
        <PackageReference Include="Swashbuckle.AspNetCore" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\BoardGameTracker.Api\BoardGameTracker.Api.csproj" />
        <ProjectReference Include="..\BoardGameTracker.Common\BoardGameTracker.Common.csproj" />
        <ProjectReference Include="..\BoardGameTracker.Core\BoardGameTracker.Core.csproj" />
        <!-- Include frontend project for local development, exclude for Docker builds -->
        <ProjectReference Include="..\boardgametracker.client\boardgametracker.client.esproj" Condition="'$(BuildWithoutEsproj)' != 'true'">
            <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
        </ProjectReference>
    </ItemGroup>

    <ItemGroup>
      <Content Include="images\no-image.jpg">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </Content>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
        <Content Include="..\Dockerfile">
            <Link>Dockerfile</Link>
        </Content>
    </ItemGroup>

</Project>
